- hosts: localhost
  vars: 
  - base_url: http://recetasbuenas.ddns.net:9925
  - packages:
    - docker.io
    - docker-compose
  - compose_files_dir: /root/compose
  - compose_apps:
    - mealie
  tasks:
  - name: install packages 
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"

  - name: Create dir for compose files
    file: path={{compose_files_dir}} state=directory

  - name: Copy compose files
    template:
      src: compose/{{ item }}.yml.j2
      dest: "{{  compose_files_dir }}/{{ item }}.yml"
    loop: "{{ compose_apps }}"

  - name: Create systemd service files
    template:
      src: compose.service.j2
      dest: /lib/systemd/system/{{ item }}.service
    loop: "{{ compose_apps }}"

  - name: Enable services
    service: 
      name: "{{ item }}"
      state: started 
      enabled: yes
    loop: "{{ compose_apps }}"
